server:
  port: 8001

#服务注册
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  #数据库连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver # com.mysql.jdbc.Driver
    url: jdbc:mysql://10.254.1.56:3306/lcc_pay_dev?useSSL=false&serverTimezone=GMT%2B8
    username: pcp
    password: pcp
    druid:
      initial-size: 3
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-log-stats-millis: 300000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      filters: stat, slf4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 10000
        slf4j:
          result-set-log-enabled: false
          statement-executable-sql-log-enable: false
      stat-view-servlet:
        enabled: true
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lcchain.mall.base.common.entity
  global-config:
    db-config:
      id-type: auto

# 描述信息
info:
  author: luohx
  mail: Lhongxiao@lcchain.com
  version: @project.version@
# 加载所有的端点/默认只加载了 info / health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    # 可以关闭制定的端点
    shutdown:
      enabled: false